spring.application.name=pierre

#----------------- configuracoes -----------------

spring.datasource.username=marco
spring.datasource.password=Abc12345
spring.datasource.databasename=master
#spring.datasource.server=jdbc:sqlserver://SQLEXPRESS
spring.datasource.url-base=${spring.datasource.server};databaseName=
#spring.datasource.url=${spring.datasource.url-base}${spring.datasource.databasename};encrypt=true;trustServerCertificate=true
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=true;trustServerCertificate=true
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=master;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
server.port=8082